<?php

namespace SqlExecutor\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-30 at 05:58:51.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Config;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
