<?php

namespace SqlExecutor\Db;

require_once dirname(dirname(__FILE__)) . "/src/Db/DbAccessor.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-05 at 10:09:50.
 */
class DbAccessorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DbAccessor
     */
    protected $object;
    protected $pdo;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        if (is_null($this->pdo)) {
            $this->pdo = new \PDO("sqlite::memory:");
            $this->pdo->exec(file_get_contents("./sql/create.sql"));
            $this->pdo->exec(file_get_contents("./sql/insert.sql"));
        }
        
        if (is_null($this->object)) {
            $this->object = new DbAccessor(array('database' => array('dsn' => 'sqlite::memory:')));
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SqlExecutor\Db\DbAccessor::query
     * @todo   Implement testQuery().
     */
    public function testQuery() {
        $stmt = $this->pdo->query("select * from user");
        $resultA = $stmt->fetch();

        $resultB = $this->object->query("select * from user");
        
        print_r($resultB);        
    }
}
