<?php

namespace SqlExecutor;

require_once dirname(dirname(__FILE__)) . "/src/SqlExecutor.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-30 at 07:47:07.
 */
class SqlExecutorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SqlExecutor
     */
    protected $object;

    protected $pdo;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SqlExecutor;
        
        if (is_null($this->pdo)) {
            $this->pdo = new \PDO("sqlite::memory:");
            $this->pdo->exec(file_get_contents("./sql/create.sql"));
            $this->pdo->exec(file_get_contents("./sql/insert.sql"));
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SqlExecutor\SqlExecutor::from
     * @todo   Implement testFrom().
     */
    public function testFrom() {
        $stmt = $this->pdo->query("select * from user");
        print_r($stmt->fetch());
    }

}
