<?php

namespace SqlExecutor;

require_once dirname(dirname(__FILE__)) . "/src/SqlExecutor.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-30 at 07:47:07.
 */
class SqlExecutorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SqlExecutor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SqlExecutor\SqlExecutor::from
     * @todo   Implement testFrom().
     */
    public function testFrom() {
    }

}
